// src/data/definitions/gameConfig.js

export const gameConfig = {
    orderTTL: 90,
    MASTERY_XP_LEVEL_START: 100,
    MASTERY_XP_LEVEL_MULTIPLIER: 1.15,
    SHOP_REPUTATION_XP_PER_SALE: 50,

    DEFAULT_MIN_TIME_BETWEEN_CLICKS: 100,

    CRAFT_XP_PROGRESS_DIVIDER: 10,
    SALE_XP_SALE_PRICE_DIVIDER: 20,
    QUEST_XP_SPARK_DIVIDER: 100,
    MISSION_XP_SPARK_DIVIDER: 50,
    ORDER_XP_PROGRESS_DIVIDER: 10,

    REFORGE_BASE_RISK: 0.2,
    REFORGE_QUALITY_DECREASE_MIN: 0.1,
    REFORGE_QUALITY_DECREASE_RANDOM: 0.2,
    REFORGE_QUALITY_INCREASE_MIN: 0.1,
    REFORGE_QUALITY_INCREASE_RANDOM: 0.3,
    REFORGE_REQUIRED_PROGRESS: 1000,
    REFORGE_XP_QUALITY_MULTIPLIER: 10,

    INLAY_BASE_RISK: 0.3,
    INLAY_QUALITY_BONUS: 0.5,
    INLAY_QUALITY_INCREASE_MIN: 0.1,
    INLAY_QUALITY_INCREASE_RANDOM: 0.2,
    INLAY_REQUIRED_PROGRESS: 800,
    INLAY_XP_QUALITY_MULTIPLIER: 15,

    GRAVING_BASE_RISK: 0.25,
    GRAVING_REQUIRED_PROGRESS: 1200,
    GRAVING_XP_LEVEL_MULTIPLIER: 20,

    RISKY_ORDER_BASE_CHANCE: 0.05,
    RISKY_ORDER_LOCKED_SHOP_CHANCE: 0.15,
    COLLECTOR_ORDER_CHANCE: 0.02,

    RISKY_ORDER_SPARK_PENALTY_MIN_MULTIPLIER: 0.05,
    RISKY_ORDER_SPARK_PENALTY_RANDOM_MULTIPLIER: 0.15,
    SHOP_LOCK_DURATION_MIN: 30,
    SHOP_LOCK_DURATION_RANDOM_MULTIPLIER: 1,
    RISKY_ORDER_BROKEN_TOOL_DURATION: 60,

    ORDER_QUEUE_MAX_LENGTH: 5,
    FACTION_ORDER_SKILL_BONUS: 0.1,
    FACTION_ORDER_REPUTATION_DIVIDER: 1000,

    PROGRESS_PER_SALE_CLICK: 10,
    SALE_BASE_PRICE_MULTIPLIER: 10,
    SALE_REQUIRED_PROGRESS_MULTIPLIER: 10,

    MINIGAME_MAX_DURATION: 10,
    MINIGAME_PENALTY_QUALITY_DECREASE: 0.1,
    MINIGAME_QUALITY_ZONE_MIN_SIZE: 10,
    MINIGAME_QUALITY_ZONE_MAX_SIZE: 20,
    MINIGAME_PERFECT_ZONE_MIN_SIZE: 2,
    MINIGAME_PERFECT_ZONE_MAX_SIZE: 5,
    MINIGAME_CLICK_POINTS_COUNT_MIN: 3,
    MINIGAME_CLICK_POINTS_COUNT_MAX: 10,
    MINIGAME_CLICK_POINT_LIFETIME_MS: 1500,
    MINIGAME_CLICK_POINT_FADE_SPEED: 0.05,

    PERSONNEL_OFFER_REFRESH_INTERVAL_MINUTES: 10,
    PERSONNEL_OFFER_ROLL_COST_MULTIPLIER: 1.5,
    personnelRollCost: { sparks: 1000 },
    PERSONNEL_OFFER_COST_REDUCTION_PER_SHOP_LEVEL: 0.005,
    WAGE_PAYMENT_INTERVAL_MINUTES: 10,
    PERSONNEL_RESIGN_CHANCE_LOW_MOOD: 0.05,
    PERSONNEL_SLOT_COOLDOWN_SECONDS: 600,
    PERSONNEL_AUTO_REST_DURATION_SECONDS: 300,
    PERSONNEL_MAX_LEVEL: 10,
    PERSONNEL_MOOD_DECAY_RATE: 0.02,
    PERSONNEL_MOOD_RECOVERY_RATE: 0.2, // НОВЫЙ ПАРАМЕТР: 0.2 настроения в секунду (60 за 5 минут отдыха)

    PERSONNEL_XP_PER_RESOURCE_TICK: 0.1,
    PERSONNEL_XP_PER_SMELT_PROGRESS: 0.01,
    PERSONNEL_XP_PER_SALE_PROGRESS: 0.02,
};