// src/constants/paths.js

// Абсолютные пути к изображениям
export const IMAGE_PATHS = {
    AVATARS: {
        DEFAULT_MALE: '/img/avatars/default_male.webp',
        DEFAULT_FEMALE: '/img/avatars/default_female.webp',
        MASTER_BLACKSMITH: '/img/avatars/master_blacksmith.webp',
        ROYAL_CRAFTSMAN: '/img/avatars/royal_craftsman.webp',
    },
    ACHIEVEMENTS: {
        MAIN_GOAL: '/img/achievements/main_goal.webp',
        FACTION_MERCHANTS: '/img/achievements/faction_merchants.webp',
        FACTION_ADVENTURERS: '/img/achievements/faction_adventurers.webp',
        FACTION_COURT: '/img/achievements/faction_court.webp',
        MASTERY_SKILLS: '/img/achievements/mastery_skills.webp',
        MASTERY_QUESTS: '/img/achievements/mastery_quests.webp',
        MASTERY_PERSONNEL: '/img/achievements/mastery_personnel.webp',
        FIRST_FORGE: '/img/achievements/first_forge.webp',
        MASTER_SMELTER: '/img/achievements/master_smelter.webp',
        FIRST_APPRENTICE_HIRE: '/img/achievements/first_apprentice_hire.webp',
        SHOP_EXPANSION: '/img/achievements/shop_expansion.webp',
        NOVICE_COLLECTOR: '/img/achievements/novice_collector.webp',
        RESOURCE_TYCOON: '/img/achievements/resource_tycoon.webp',
        INLAY_MASTER: '/img/achievements/inlay_master.webp',
        GRAVING_LEGEND: '/img/achievements/graving_legend.webp',
        VETERAN_CRAFTER: '/img/achievements/veteran_crafter.webp',
        DILIGENT_SMELTER: '/img/achievements/diligent_smelter.webp',
        TREASURER: '/img/achievements/treasurer.webp',
        MATTER_ESSENCE_MASTER: '/img/achievements/matter_essence_master.webp',
        FIRST_RESETTLEMENT: '/img/achievements/first_resettlement.webp',
        WORLD_EXPLORER: '/img/achievements/world_explorer.webp',
        PEAK_MASTERY: '/img/achievements/peak_mastery.webp',
        ENHANCED_CLICKER: '/img/achievements/enhanced_clicker.webp',
        PATHFINDERS_FIRST_STEP: '/img/achievements/pathfinders_first_step.webp',
        ROYAL_FORGER: '/img/achievements/royal_forger.webp',
        SECRET_AGENT: '/img/achievements/secret_agent.webp',
        ADVENTURERS_CARTOGRAPHER: '/img/achievements/adventurers_cartographer.webp',
        DEFAULT: '/img/achievements/default.webp',
    },
    CLIENTS: {
        FARMER: '/img/clients/farmer.webp',
        ADVENTURER: '/img/clients/adventurer.webp',
        NOBLE: '/img/clients/noble.webp',
        SHADOWY_FIGURE: '/img/clients/shadowy_figure.webp',
        COLLECTOR: '/img/clients/collector.webp',
        ALCHEMIST: '/img/clients/alchemist.webp',
        SCHOLAR: '/img/clients/scholar.webp',
        BARBARIAN: '/img/clients/barbarian.webp',
        BARD: '/img/clients/bard.webp',
        ARTISAN: '/img/clients/artisan.webp',
        MINER: '/img/clients/miner.webp',
        HUNTER: '/img/clients/hunter.webp',
        PRIESTESS: '/img/clients/priestess.webp',
        ENGINEER_CLIENT: '/img/clients/engineer_client.webp',
        SPY: '/img/clients/spy.webp',
    },
    ITEMS: {
        NAIL: '/img/items/nail.webp',
        HORSESHOE: '/img/items/horseshoe.webp',
        DAGGER: '/img/items/dagger.webp',
        IRON_HELMET: '/img/items/iron_helmet.webp',
        IRON_GREAVES: '/img/items/iron_greaves.webp',
        TWO_HANDED_AXE: '/img/items/two_handed_axe.webp',
        REINFORCED_SHIELD: '/img/items/reinforced_shield.webp',
        COPPER_BRACELET: '/img/items/copper_bracelet.webp',
        COPPER_AMULET: '/img/items/copper_amulet.webp',
        BRONZE_SHIELD: '/img/items/bronze_shield.webp',
        BRONZE_SWORD: '/img/items/bronze_sword.webp',
        BRONZE_CUIRASS: '/img/items/bronze_cuirass.webp',
        BRONZE_GAUNTLETS: '/img/items/bronze_gauntlets.webp',
        BRONZE_HELMET: '/img/items/bronze_helmet.webp',
        BRONZE_GREAVES: '/img/items/bronze_greaves.webp',
        SPARKSTEEL_MACE: '/img/items/sparksteel_mace.webp',
        ORNATE_GREATSWORD: '/img/items/ornate_greatsword.webp',
        ROYAL_CROWN: '/img/items/royal_crown.webp',
        MITHRIL_DAGGER: '/img/items/mithril_dagger.webp',
        MITHRIL_SHIELD: '/img/items/mithril_shield.webp',
        MITHRIL_LONGSWORD: '/img/items/mithril_longsword.webp',
        MITHRIL_CHAINMAIL: '/img/items/mithril_chainmail.webp',
        ADAMANTITE_PLATEBODY: '/img/items/adamantite_platebody.webp',
        ARCANITE_SPELLBLADE: '/img/items/arcanite_spellblade.webp',
        CRAFTABLE_ADAMANTITE_CORE: '/img/items/adamantite_core.webp',
        CRAFTABLE_RUNE_OF_FORTITUDE: '/img/items/stabilizing_gyroscope.webp',
        CRAFTABLE_PURIFIED_MITHRIL: '/img/items/purified_mithril.webp',
        CRAFTABLE_FOCUSING_LENS: '/img/items/focusing_lens.webp',
        IRON_CROWBAR: '/img/items/iron_crowbar.webp',
        COPPER_CAULDRON: '/img/items/copper_cauldron.webp',
        BRONZE_GREATAXE: '/img/items/bronze_greataxe.webp',
        SPARKSTEEL_TOOLSET: '/img/items/sparksteel_toolset.webp',
        IRON_VICE: '/img/items/iron_vice.webp',
        COPPER_CHAIN: '/img/items/copper_chain.webp',
        BRONZE_HAMMER: '/img/items/bronze_hammer.webp',
        ARMOR_REPAIR_KIT: '/img/items/armor_repair_kit.webp',
        MITHRIL_BOW: '/img/items/mithril_bow.webp',
        ADAMANTITE_HELMET: '/img/items/adamantite_helmet.webp',
        ARCANITE_AMULET: '/img/items/arcanite_amulet.webp',
        SPARKSTEEL_JEWELERS_KIT: '/img/items/sparksteel_jewelers_kit.webp',
        SPARKSTEEL_CROSSBOW: '/img/items/sparksteel_crossbow.webp',
        SPARKSTEEL_PINCERS: '/img/items/sparksteel_pincers.webp',
        SPARKSTEEL_ARMOR_PLATES: '/img/items/sparksteel_armor_plates.webp',
        SPARKSTEEL_WATCH: '/img/items/sparksteel_watch.webp',
        // Материалы артефактов (также являются specialItems)
        MATERIAL_GUARDIAN_HEART: '/img/items/guardian_heart.webp',
        MATERIAL_ADAMANT_FRAME: '/img/items/adamant_frame.webp',
        MATERIAL_LAVA_AGATE: '/img/items/lava_agate.webp',
        MATERIAL_IRONWOOD_HANDLE: '/img/items/ironwood_handle.webp',
        MATERIAL_SUN_TEAR: '/img/items/sun_tear.webp',
        MATERIAL_PURIFIED_GOLD: '/img/items/purified_gold.webp',
    },
    INGOTS: {
        IRON: '/img/ingots/iron_ingot.webp',
        COPPER: '/img/ingots/copper_ingot.webp',
        MITHRIL: '/img/ingots/mithril_ingot.webp',
        ADAMANTITE: '/img/ingots/adamantite_ingot.webp',
        BRONZE: '/img/ingots/bronze_ingot.webp',
        SPARKSTEEL: '/img/ingots/sparksteel_ingot.webp',
        ARCANITE: '/img/ingots/arcanite_ingot.webp',
    },
    ORES: {
        IRON: '/img/ores/iron_ore.webp',
        COPPER: '/img/ores/copper_ore.webp',
        MITHRIL: '/img/ores/mithril_ore.webp',
        ADAMANTITE: '/img/ores/adamantite_ore.webp',
    },
    ARTIFACTS: {
        AEGIS: '/img/artifacts/aegis_shield.webp',
        HAMMER: '/img/artifacts/mountain_heart_hammer.webp',
        CROWN: '/img/artifacts/sun_crown.webp',
        BASTION: '/img/artifacts/bastion_of_invincibility.webp',
        QUILL: '/img/artifacts/archivists_quill.webp',
    },
    UI: {
        ANVIL: '/img/ui/anvil.webp',
    }
};

// Абсолютные пути к аудиофайлам
export const AUDIO_PATHS = {
    MUSIC: [
        '/audio/cithare-medieval-1-307558.mp3',
        '/audio/fantasy-medieval-ambient-237371.mp3',
        '/audio/fantasy-medieval-mystery-ambient-292418.mp3',
        '/audio/medieval-ambient-236809.mp3',
        '/audio/medieval-background-196571.mp3',
        '/audio/medieval-background-351307.mp3',
        '/audio/medieval-citytavern-ambient-235876.mp3',
        '/audio/medieval-track-161051.mp3',
        '/audio/the-ballad-of-my-sweet-fair-maiden-medieval-style-music-358306.mp3',
    ],
};