// src/constants/ui.js
import { IMAGE_PATHS } from './paths'; // Импортируем новые пути

export const UI_CONSTANTS = {
    DEFAULT_AVATAR_SRC: IMAGE_PATHS.AVATARS.DEFAULT_MALE,
    PLACEHOLDER_ITEM_SRC: (size) => `https://placehold.co/${size}x${size}/333/FFF?text=ITEM`,
    PLACEHOLDER_RESOURCE_SRC: (size, text) => `https://placehold.co/${size}x${size}/333/FFF?text=${text}`,
    PLACEHOLDER_ARTIFACT_SRC: (size) => `https://placehold.co/${size}x${size}/333/FFF?text=ART`,
    PLACEHOLDER_ACHIEVEMENT_SRC: IMAGE_PATHS.ACHIEVEMENTS.DEFAULT,

    ICON_MAP: {
        sparks: { icon: 'bolt', class: 'text-yellow-400' },
        matter: { icon: 'bubble_chart', class: 'text-purple-400' },
        ironOre: { icon: IMAGE_PATHS.ORES.IRON, class: '' },
        copperOre: { icon: IMAGE_PATHS.ORES.COPPER, class: '' },
        mithrilOre: { icon: IMAGE_PATHS.ORES.MITHRIL, class: '' },
        adamantiteOre: { icon: IMAGE_PATHS.ORES.ADAMANTITE, class: '' },
        ironIngots: { icon: IMAGE_PATHS.INGOTS.IRON, class: '' },
        copperIngots: { icon: IMAGE_PATHS.INGOTS.COPPER, class: '' },
        bronzeIngots: { icon: IMAGE_PATHS.INGOTS.BRONZE, class: '' },
        sparksteelIngots: { icon: IMAGE_PATHS.INGOTS.SPARKSTEEL, class: '' },
        mithrilIngots: { icon: IMAGE_PATHS.INGOTS.MITHRIL, class: '' },
        adamantiteIngots: { icon: IMAGE_PATHS.INGOTS.ADAMANTITE, class: '' },
        arcaniteIngots: { icon: IMAGE_PATHS.INGOTS.ARCANITE, class: '' },
        gem: { icon: 'diamond', class: 'text-pink-400' },
        expeditionMap: { icon: 'map', class: 'text-yellow-600' },
        material_guardianHeart: { icon: IMAGE_PATHS.ITEMS.MATERIAL_GUARDIAN_HEART, class: ''},
        material_adamantFrame: { icon: IMAGE_PATHS.ITEMS.MATERIAL_ADAMANT_FRAME, class: ''},
        material_lavaAgate: { icon: IMAGE_PATHS.ITEMS.MATERIAL_LAVA_AGATE, class: ''},
        material_ironwoodHandle: { icon: IMAGE_PATHS.ITEMS.MATERIAL_IRONWOOD_HANDLE, class: ''},
        material_sunTear: { icon: IMAGE_PATHS.ITEMS.MATERIAL_SUN_TEAR, class: ''},
        material_purifiedGold: { icon: IMAGE_PATHS.ITEMS.MATERIAL_PURIFIED_GOLD, class: ''},
        component_adamantiteCore: { icon: IMAGE_PATHS.ITEMS.CRAFTABLE_ADAMANTITE_CORE, class: ''},
        component_stabilizingGyroscope: { icon: IMAGE_PATHS.ITEMS.CRAFTABLE_RUNE_OF_FORTITUDE, class: ''},
        component_purifiedMithril: { icon: IMAGE_PATHS.ITEMS.CRAFTABLE_PURIFIED_MITHRIL, class: ''},
        component_focusingLens: { icon: IMAGE_PATHS.ITEMS.CRAFTABLE_FOCUSING_LENS, class: ''},
        blueprint_aegis: { icon: 'auto_stories', class: 'text-blue-400' },
        blueprint_hammer: { icon: 'auto_stories', class: 'text-blue-400' },
        blueprint_crown: { icon: 'auto_stories', class: 'text-blue-400' },
        blueprint_bastion: { icon: 'auto_stories', class: 'text-blue-400' },
        blueprint_quill: { icon: 'auto_stories', class: 'text-blue-400' },
    },
    RESOURCE_NAMES: {
        sparks: 'искр',
        matter: 'материи',
        ironOre: 'жел. руды',
        copperOre: 'медн. руды',
        mithrilOre: 'мифр. руды',
        adamantiteOre: 'адам. руды',
        ironIngots: 'жел. сл.',
        copperIngots: 'медн. сл.',
        bronzeIngots: 'бронз. сл.',
        sparksteelIngots: 'искр. сл.',
        mithrilIngots: 'мифр. сл.',
        adamantiteIngots: 'адам. сл.',
        arcaniteIngots: 'аркан. сл.',
        gem: 'самоцветы',
        expeditionMap: 'карт вылазок',
        default: 'ед.',
    },
    TOOLTIP_DELAY: 500,
};